version: '3.1'


services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    environment:
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.server.waitTimeInMsWhenSyncEmpty=0
      - management.tracing.sampling.probability=1.0
      - management.endpoints.web.exposure.include=prometheus
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment: &shared_env
      - eureka.instance.preferIpAddress=true
      - eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
      - spring.datasource.url=jdbc:mysql://db:3306/lms_db_spring
      - spring.datasource.username=root
      - spring.datasource.password=password
    depends_on:
      - service-registry
    networks:
      - backend

  attachment-service:
    build:
      context: ./attachment-service
    ports:
      - "8083:8083"
    environment: *shared_env
    depends_on:
      - service-registry
      - api-gateway
      - db
    networks:
      - backend

  category-service:
    build:
      context: ./category-service
    ports:
      - "8084:8084"
    environment: *shared_env
    depends_on:
      - service-registry
      - api-gateway
      - db
    networks:
      - backend

  course-service:
    build:
      context: ./course-service
    ports:
      - "8081:8081"
    environment: *shared_env
    depends_on:
      - service-registry
      - api-gateway
      - db
      - category-service
      - chapter-service
    networks:
      - backend

  user-progress-service:
    build:
      context: ./user-progress-service
    ports:
      - "8085:8085"
    environment: *shared_env
    depends_on:
      - service-registry
      - api-gateway
      - db
    networks:
      - backend

  chapter-service:
    build:
      context: ./chapter-service
    ports:
      - "8082:8082"
    environment: *shared_env
    depends_on:
      - service-registry
      - api-gateway
      - db
      - user-progress-service
    networks:
      - backend

  mux-service:
    build:
      context: ./muxData-service
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/lms_db_mux?schema=public
      - EUREKA_HOST=service-registry
    depends_on:
      - service-registry
      - api-gateway
      - db
    networks:
      - backend
volumes:
  db_data:

networks:
  backend: